backend/modules/administrator/controllers/DefaultController.php
<?php

namespace app\modules\administrator\controllers;

use Yii;

use common\models\Post;
use common\models\User;
use common\models\Page;

use yii\web\Controller;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;

use app\modules\administrator\models\Message;
use yii\db\Query;

use yii\helpers\ArrayHelper;
use linslin\yii2\curl;

class DefaultController extends Controller {
	public function behaviors() {
		return [
			'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                    	'allow' => true,
                    	'roles' => ['administrator'],
                    ],
                ],
            ],
        ];
	}
    public function actionIndex() {
        $post = new Post();
        $latestPosts = Post::find()
            ->limit(3)
            ->orderBy(['id' => SORT_DESC])
            ->all();
        $users = User::find()->count();
        $posts = Post::find()->count();
        $pages = Page::find()->count();
        return $this->render('index', [
            'post' => $post,
            'latestPosts' => $latestPosts,
            'users' => $users,
            'posts' => $posts,
            'pages' => $pages,
        ]);
    }
}

backend/modules/administrator/controllers/PageController.php
<?php

namespace app\modules\administrator\controllers;

use Yii;
use common\models\Page;
use common\models\PageSearch;
use common\models\SiteMenu;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\helpers\Url;

/**
 * PageController implements the CRUD actions for Page model.
 */
class PageController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Page models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new PageSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Page model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Page model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Page();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Page model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Page model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Page model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Page the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Page::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/modules/administrator/controllers/PostController.php
<?php

namespace app\modules\administrator\controllers;

use Yii;
use common\models\Post;
use common\models\PostSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\modules\administrator\controllers\DefaultController;

/**
 * PostController implements the CRUD actions for Post model.
 */
class PostController extends DefaultController
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Post models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new PostSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Post model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Post model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Post();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Post model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Post model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Post model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Post the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Post::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/modules/administrator/controllers/UserController.php
<?php

namespace app\modules\administrator\controllers;

use Yii;
use common\models\User;
use common\models\UserSearch;
use common\models\AuthAssignment;
use common\models\Administrator;
use common\models\Author;
use common\models\Editor;
use common\models\Comment;


use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\modules\administrator\models\SignupForm;
use app\modules\administrator\controllers\DefaultController;
use yii\data\SqlDataProvider;
/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends DefaultController
{
	 /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }


	public function actionProfile($id)
    {
        $model = $this->findModel($id);
		$profile = AuthAssignment::find()->where(['user_id'=>$id])->one();
			
		switch($profile->item_name){
			case 'administrator':
				$this->redirect(['administrator/view', 'id' => $id]);
				break;
			case 'editor':
				$this->redirect(['editor/view', 'id' => $id]);
				break;
			case 'author':
				$this->redirect(['author/view', 'id' => $id]);
				break;
		}
    }
	
    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
        	$model->save();
            return $this->redirect(['index']);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
		$model=$this->findModel($id);
        if($model->id==Yii::$app->user->identity->id){
            Yii::$app->getSession()->setFlash('error', 'Невозможно удалить свой профайл');
        }else{
            $model->delete();
        }

        if(file_exists(Yii::getAlias('@uploads')."/".Yii::getAlias('@articlesPath')."/".$id))
        {
            $folders=glob(Yii::getAlias('@uploads')."/".Yii::getAlias('@articlesPath')."/".$id."/*");
            if(!empty($folders)){
                foreach($folders as $folder){
                    $files=glob($folder."/*.*");
                    foreach ($files as $f) {
                        unlink($f);
                    }
                    rmdir($folder);
                }
            }
           rmdir(Yii::getAlias('@uploads')."/".Yii::getAlias('@articlesPath')."/".$id);
        }
        //delete all user files and folders in contests folder
        $contest_folders=glob(Yii::getAlias('@uploads')."/".Yii::getAlias('@contestsPath'."/*"));
        $user_folders=array();
        $files=array();
        if(!empty($contest_folders)){
            foreach ($contest_folders as $folders){
                $tmp=glob($folders."/".$id);
                if(!empty($tmp)) 
                {
                    array_push($user_folders, $tmp[0]);
                }
            }
            if(!empty($user_folders))
            {
                foreach ($user_folders as $user_folder){
                    $user_files=glob($user_folder."/*");
                    if(!empty($user_files)){
                        foreach($user_files as $f){
                            unlink($f);
                        }
                    }
                    rmdir($user_folder);
                }
            }
        }
	   return $this->redirect(['index']); 
    } 


    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
	
	public function actionSignup()
    {
		$model = new SignupForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()) {
				$userRole = Yii::$app->authManager->getRole($model->role_name);
				Yii::$app->authManager->assign($userRole, $user->getId());

				switch($model->role_name){
					case 'administrator':
						$this->redirect(['administrator/create']);
						break;
					case 'editor':
						$this->redirect(['editor/create']);
						break;
					case 'author':
                        mkdir(Yii::getAlias('@uploads')."/".Yii::getAlias('@articlesPath')."/".$user->getId()."/");
                        $this->redirect(['author/create']);
						break;
					}
					return;
				}	
            }
        return $this->render('signup', [
            'model' => $model,
        ]);
    }
	
    protected function getAdministratorById($id) 
    {
        if (($model = Administrator::findOne($id)) !== null){
            return $model;
        }else{
        	throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
     

    protected function getEditorById($id) {
        if (($model = Editor::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    protected function getAuthorById($id) 
    {
        if(($model = Author::findOne($id)) !== null) {
            return $model;
        }else{
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
		
}

backend/modules/administrator/views/default/_latest_posts.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;

?>
<div class="well shadow-0">
        <h4>Последние записи</h4>
        <hr class="blue-border-color">
        <?php foreach ($posts as $post) { ?>

        	<?= Html::beginTag('a', ['href' => Url::to(['post/view', 'id' => $post->id], true)]) ?>

        		<?= Html::beginTag('p') ?>

        			<?= Html::tag('time', Html::decode($post->publish_date)) ?>

        			<?= Html::tag('br') ?>

        			<?= Html::tag('span', Html::decode($post->title)) ?>

        		<?= Html::endTag('p') ?>

        	<?= Html::endTag('a') ?>

                <?= Html::tag('hr') ?>

        <?php } ?>
</div>

backend/modules/administrator/views/default/_quick_post_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\Post */
/* @var $form yii\widgets\ActiveForm */
?>
<div class="well shadow-0">
    <h4>Быстрая запись</h4>
    <hr class="blue-border-color">
    <div class="post-form">

        <?php $form = ActiveForm::begin(['action' => ['post/create']]); ?>
                    
            <?= $form->field($post, 'title')->textInput(['maxlength' => true]) ?>

            <?= $form->field($post, 'content')->textArea(['rows' => '3', 'style' => 'resize:none']) ?>

            <?= $form->field($post, 'preview')->textArea(['rows' => '2', 'style' => 'resize:none']) ?>

            <div class="form-group">

                <?= Html::submitButton($post->isNewRecord ? 'Создать' : 'Обновить', ['class' => $post->isNewRecord ? 'btn btn-primary' : 'btn btn-success']) ?>
                        
            </div>

        <?php ActiveForm::end(); ?>

    </div>
</div>

backend/modules/administrator/views/default/_statistic.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;

?>

<div class="well shadow-0">
	<h4>Статистика</h4>
    <hr class="blue-border-color">
    <p>

    	<?= Html::beginTag('a', ['href' => Url::to(['user/index'], true)]) ?>

    		<span class="glyphicon glyphicon-user" aria-hidden="true"></span>
    		<span>Пользователей - <?= ($users) ? ($users) : ('-') ?></span>

    	<?= Html::endTag('a') ?>

    </p>
    <p>

    	<?= Html::beginTag('a', ['href' => Url::to(['page/index'], true)]) ?>

	    	<span class="glyphicon glyphicon-file" aria-hidden="true"></span>
	    	<span>Страниц - <?= ($pages) ? ($pages) : ('-') ?></span>

    	<?= Html::endTag('a') ?>
    </p>
    <p>

    	<?= Html::beginTag('a', ['href' => Url::to(['post/index'], true)]) ?>

	    	<span class="glyphicon glyphicon-pushpin" aria-hidden="true"></span>
	    	<span>Записей - <?= ($posts) ? ($posts) : ('-') ?></span>
    	
    	<?= Html::endTag('a') ?>
    </p>
</div>

backend/modules/administrator/views/default/index.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;

?>
<div class="administrator-default-index">
	<div class="jumbotron shadow-0" style="background-color: #eee">
	  	<h2>
        	<p class="alert alert-success">Добро пожаловать в административную панель сайта IT & TRANSPORT</p>    
    	</h2>
	</div>
    <div class="row">
    	<div class="col-md-4">
    			
			<?= $this->render('_quick_post_form', [
    			'post' => $post,
			]) ?>

    	</div>
    	<div class="col-md-4">

			<?= $this->render('_latest_posts', [
    			'posts' => $latestPosts,
			]) ?>

    	</div>
    	<div class="col-md-4">

    		<?= $this->render('_statistic', [
    			'users' => $users,
    			'pages' => $pages,
    			'posts' => $posts
    		]) ?>
    		
    	</div>
    </div>
</div>