backend/modules/author/controllers/ContestArticleReturnedController.php
<?php

namespace app\modules\author\controllers;

use Yii;
use common\models\ContestArticle;
use common\models\ContestArticleSearch;
use common\models\ContestArticleUploadForm;
use common\models\ContestComment;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\ForbiddenHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;
use yii\data\ActiveDataProvider;

/**
 * ContestArticleController implements the CRUD actions for ContestArticle model.
 */
class ContestArticleReturnedController extends ContestArticleDraftController
{

    public function actionView($id)
    {
        $model=$this->findModel($id);

        $comments=$this->getArticleComments($id);

        $comment = new ContestComment();

        if($model->user_id==Yii::$app->user->identity->id && $model->status==Yii::$app->params['returned'])
        {
            return $this->render('view', [
                'comment' => $comment,
                'comments' => $comments,
                'model' => $model,
            ]);
        }else{
            throw new ForbiddenHttpException('The requested page does not exist for you.');
        }
    }


    protected function getArticleComments($article_id)
    {
        $comments = ContestComment::find()->where(['cn_article_id'=>$article_id])->all(); 
            return $comments;
    }

    public function actionComment($id)
    {
        $comment = new ContestComment();
        $comment->comment=Yii::$app->request->post('ContestComment')['comment'];
        $comment->created_at=date('Y-m-d H:i:s');
        $comment->user_id=Yii::$app->user->identity->id;
        $comment->cn_article_id=$id;
        if(!$comment->save()){
            Yii::$app->getSession()->setFlash('error', 'Не удалось добавить комментарий');
        }
        return $this->redirect(['view', 'id' => $id]);
    } 

    protected function findModel($id)
    {
        if (($model = ContestArticle::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/modules/author/controllers/ContestController.php
<?php

namespace app\modules\author\controllers;

use Yii;
use common\models\Contest;
use common\models\ContestArticle;
use common\models\ContestSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\data\ActiveDataProvider;
use yii\helpers\Url;

/**
 * ContestController implements the CRUD actions for Contest model.
 */
class ContestController extends DefaultController
{
    /**
     * Lists all Contest models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ContestSearch();
        $dataProvider = new ActiveDataProvider([
            'query' => Contest::find()
                ->where(['<=','start_date', date('Y-m-d')])
                ->andWhere(['>=','end_date', date('Y-m-d')])
            ]);

        $draftDataProvider = new ActiveDataProvider([
            'query' => ContestArticle::find()
                ->where(['status'=> Yii::$app->params['draft']])
                ->andWhere(['user_id'=>Yii::$app->user->identity->id])
                ->joinWith('contest')
                ->orderBy('contest.end_date DESC'),
            //'sort' => false,
        ]);        

        $reviewDataProvider = new ActiveDataProvider([
            'query' => ContestArticle::find()
                ->where(['status'=> Yii::$app->params['review']])
                ->andWhere(['user_id'=>Yii::$app->user->identity->id])
                ->joinWith('contest')
                ->orderBy('contest.end_date DESC'),
            //'sort' => false,
        ]);

        $returnedDataProvider = new ActiveDataProvider([
            'query' => ContestArticle::find()
                ->where(['status'=> Yii::$app->params['returned']])
                ->andWhere(['user_id'=>Yii::$app->user->identity->id])
                ->joinWith('contest')
                ->orderBy('contest.end_date DESC'),
            //'sort' => false,
        ]);

        $acceptedDataProvider = new ActiveDataProvider([
            'query' => ContestArticle::find()
                ->where(['status'=> Yii::$app->params['accepted']])
                ->andWhere(['user_id'=>Yii::$app->user->identity->id])
                ->joinWith('contest')
                ->orderBy('contest.end_date DESC'),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'draftDataProvider' => $draftDataProvider,
            'reviewDataProvider' => $reviewDataProvider,
            'returnedDataProvider' => $returnedDataProvider,
            'acceptedDataProvider' => $acceptedDataProvider,
        ]);
    }

    /**
     * Displays a single Contest model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }


    /**
     * Creates a new Contest model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    protected function findModel($id)
    {
        if (($model = Contest::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}            

backend/modules/author/views/contest-article-returned/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use common\models\ContestNomination;
use common\models\Master;
use yii\bootstrap\Modal;
use kartik\select2\Select2;

/* @var $this yii\web\View */
/* @var $model frontend\models\ContestArticle */
/* @var $form yii\widgets\ActiveForm */

?>

<div class="contest-article-form" ng-app="authorApp">

    <?php 
        Modal::begin([
            'header' => 'Добавить руководителя',
            'id' => 'editModalId',
            'class' => 'modal',
            'size' => 'modal-md',
        ]);

    ?>

        <div id="time-progressbar" class="progress">
          <div class="progress-bar progress-bar-striped active" role="progressbar" aria-valuenow="45" aria-valuemin="0" aria-valuemax="100" style="width: 45%">
            <span class="sr-only">45% Complete</span>
          </div>
        </div>
        <div class='modalContent'></div>

    <?php

        Modal::end();

    ?>

    <?php $form = ActiveForm::begin((['options' => ['enctype' => 'multipart/form-data']]) ); ?>

    <?= $form->field($model, 'title')->textInput(['maxlength' => true]) ?>

    <fieldset class="fieldset-style">
        <legend class="legend-style">Руководитель</legend>      

        <?= $form->field($cn_article_masters, 'master_id')->widget(Select2::classname(), [
                    'data' => ArrayHelper::map(Master::find()->orderBy('surname')->all(),'id',
                        function($model){
                            return $model->surname . ' ' . $model->name . ' ' . $model->lastname . ' - ' . $model->organization;
                        }),
                    'toggleAllSettings' => [
                            'selectLabel' => '<i></i>',
                        ],
                    'maintainOrder' => true,
                    'options' => ['placeholder' => 'Введите ФИО ...', 'id' => 'masterList'],
                    'pluginOptions' => [
                        'allowClear' => true,
                        'multiple' => true,
                        'minimumInputLength' => 2,
                        'maximumSelectionLength' => 2,
                    ],
                ])->label('Укажите руководителя (не более 2-х)'); ?>

            <div class="col-md-12">
                <span>Если Вы не нашли своего научного руководителя в списке - добавьте его</span>
                <?= Html::a('<span class="fa fa-user-plus">', ['master-create'], ['class'=>'btn btn-default modalButton', 'title' => 'Добавить руководителя в базу']) ?>
            </div>          

    </fieldset>
    
    <fieldset ng-controller="CoauthorsController" class="fieldset-style">
        <legend class="legend-style">Автор</legend>

        <?= $form->field($model, 'author')->textInput(['maxlength' => true, 'placeholder' => 'ФИО автора']) ?>
        
        <?= $form->field($model, 'organization')->textInput(['maxlength' => true, 'placeholder' => 'Название организации']) ?>

        <?= $form->field($model, 'coauthor')->textInput(['maxlength' => true, 'readonly' => 'true', 'style' => 'display: none', 'id' => 'article-coauthor']) ?>
        
        <div class="panel-group" id="accordion">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4 class="panel-title">
                        <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
                            Добавить соавторов
                        <span class="fa fa-user-plus"></span></a>
                    </h4>
                </div>
                <div id="collapseOne" class="panel-collapse collapse">
                    <div class="panel-body">
                        <div class="row" style="display:block">
                            <div class="col-md-8">
                                <div class="input-group">
                                    <span class="input-group-addon" id="basic-addon1"><span class="glyphicon glyphicon-user" aria-hidden="true"></span></span>
                                    <input id="newCoauthor" ng-model="coathor" ng-keydown="$event.keyCode == 13 ? addCoathor($event) : null" type="text" class="form-control" placeholder="Фамилия И.О. соавтора" aria-describedby="basic-addon1">
                                </div>
                            </div>
                            <div class="col-md-2">
                                <button type="button" class="btn btn-success" ng-click="addCoathor($event)" ng-disabled="(coathor) ? (false) : (true)">Добавить</button>
                            </div>
                        </div>
                        <ul class="list-group row-margin coauthors-list">
                            <li class="list-group-item" ng-repeat="author in coauthors track by $index">
                                {{author}}
                                <div class="pull-right action-buttons">
                                    <a href="" class="trash" ng-click="removeCoathor($index)"><span class="glyphicon glyphicon-remove"></span></a>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </fieldset>

    <?= $form->field($model, 'cn_nomination_id')->dropDownList(ArrayHelper::map(
        ContestNomination::find()->all(), 'id', 'nomination_name'), 
        ['prompt' => 'Выберите номинацию...'])
    ?>

     <?= $form->field($model, 'annotation')->textarea(['rows' => 6]) ?>
    
    <fieldset ng-controller="FileController" class="fieldset-style">
        <legend class="legend-style">Файл работы</legend>
        
        <div class="row" id="file" style= <?= empty($file) ? 'display:none' : 'display:true' ?> >
            <div class="col-md-2">
                <img src="../../img/file.jpg" class="img-responsive img-thumbnail">
            </div>
            <div class="col-md-1">
                <div class="pull-left action-buttons">
                    <a href="" class="trash" ng-click="removeFile()"><span class="glyphicon glyphicon-remove" title="Удалить файл работы"></span></a>
                </div>
            </div>
        </div>
        
        <div class="row" id="file-form" style= <?= empty($file) ? 'display:true' : 'display:none' ?> >
            <div class="col-md-8 offset-1">
                <?= $form->field($contest_article, 'file')->fileInput() ?>
            </div>
        </div>

    </fieldset>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Добавить' : 'Обновить', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/modules/author/views/contest-article-returned/_master-form.php
<?php
/* @var $this yii\web\View */

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use common\models\AcademicDegree;
use yii\helpers\ArrayHelper;

?>
<div id="master-form">

	<?php
		$form = ActiveForm::begin([
			'id' => 'modal-form'
		]);
	?>

		<div class="alert alert-danger" role="alert" style="display: none"></div>

		<div class="row">
			<div class="col-md-6">
				<?= $form->field($model, 'surname')->textInput(['maxlength' => true]) ?>
			</div>
			<div class="col-md-6">
				<?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>
			</div>			
		</div>	

		<div class="row">
			<div class="col-md-8">	
				<?= $form->field($model, 'lastname')->textInput(['maxlength' => true]) ?>
			</div>
			<div class="col-md-4">
				<?= $form->field($model, 'sex')->dropDownList([
                'Мужской' => 'Мужской',
                'Женский' => 'Женский',
                ], ['prompt' => 'Выберите пол...']) ?>
			</div>
		
		</div>
		<div class="row">
			<div class="col-md-12">	
				<?= $form->field($model, 'organization')->textInput(['maxlength' => true]) ?>
			</div>
		</div>

		<div class="row">
			<div class="col-md-6">
				<?= $form->field($model, 'office_position')->textInput(['maxlength' => true]) ?>
			</div>
			<div class="col-md-6">
				<?= $form->field($model, 'academic_degree_id')->dropDownList(ArrayHelper::map(
        				AcademicDegree::find()->all(), 'id', 'academic_degree'), 
        			['prompt' => 'Выберите научную степень...'])
    			?>
			</div>
		</div>
			
			

		<div class="form-group">
			
			<?= Html::submitButton($model->isNewRecord ? 'Добавить' : 'Редактировать', 
				['class' => $model->isNewRecord ? 'btn btn-success':'btn btn-primary']) ?>
		</div>

	<?php ActiveForm::end(); ?>

</div>

backend/modules/author/views/contest-article-returned/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel frontend\models\ContestArticleSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'На доработку';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="contest-article-index">

    <h3>
        <?= Html::tag('p', Html::encode($this->title), ['class' => 'alert alert-success text-center']) ?>
    </h3>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        //'filterModel' => $searchModel,
        'layout' => "{items}",
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'title',
            [
            'attribute'=>'cn_nomination_id',
            'value'=>'contestNomination.nomination_name',
            ],
            [
            'attribute'=>'contest_id',
            'value'=>'contest.name',
            ],

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>

</div>

backend/modules/author/views/contest-article-returned/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model frontend\models\ContestArticle */

$this->title = 'Обновить работу';
$this->params['breadcrumbs'][] = ['label' => 'На доработку', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => 'Работа для конкурса', 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Обновить';
?>
<div class="contest-article-update">

    <h3>
        <?= Html::tag('p', Html::encode($this->title), ['class' => 'alert alert-success text-center']) ?>
    </h3>

    <?= $this->render('_form', [
        'model' => $model,
        'contest_article'=>$contest_article,
        'cn_article_masters' => $cn_article_masters,
        'file' => $file,
    ]) ?>

</div>

backend/modules/author/views/contest-article-returned/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model frontend\models\ContestArticle */

$this->title = $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Конкурс', 'url' => ['contest/index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="contest-article-view">

    <div class="panel panel-info">
        <div class="panel-heading"><h3><?= Html::encode($this->title) ?></h3></div> 


    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
           
            'title',
            [
            'attribute' => 'master',
            'value' => $model->getMaster(),
            ],
            'author',
            'coauthor',
            'organization',
            [
            'attribute' => 'status',
            'value' => $model->getStatus($model),
            ],
            [
            'attribute' => 'cn_nomination_id',
            'value' => $model->getNomination($model->cn_nomination_id),
            ],
            [
            'attribute' => 'contest_id',
            'value' => $model->getContestName($model->contest_id),
            ],
            [
            'label' => 'Прикрепленные файлы',
            'value' => $model->getAttachedFiles($model),
            'format' => 'raw',
            ],
            'annotation',
        ],
    ]) ?>

    </div>

    <p>
        <?= Html::a('Обновить', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Удалить', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Вы уверены, что хотите удалить эту работу?',
                'method' => 'post',
            ],
        ]) ?>
        <?= Html::a('Отправить на проверку', ['submit', 'id' => $model->id], ['class' => 'btn btn-success']) ?>
    </p>

    <div class="row col-md-12" style="padding:1%">

    <?php $form = ActiveForm::begin([
        'method' => 'post',
        'action' => ['comment','id'=>$model->id],
        ]); 
    ?>

    <?= $form->field($comment, 'comment')->textarea(['maxlength' => true]) ?>

    <?= Html::submitButton('Добавить комментарий', ['class' => 'btn btn-primary']) ?>

    <?php  ActiveForm::end();  ?>
    
    </div>

    <div class="row col-md-12">
    <?php   
        if(!empty($comments)){
            $comments=array_reverse($comments);
            foreach ($comments as $v) {
                echo('<div class="panel panel-primary">');
                    echo('<div class="panel-heading">');
                        echo('<div class="row">');
                            echo('<div class="col-md-6" text-left>');
                            echo('<h4>'.$v->user->username.'</h4>');
                            //get array of all user roles and print description of roles
                            echo('<h6>'); 
                            foreach(Yii::$app->authManager->getRolesByUser($v->user_id) as $role){
                                echo(Html::encode($role->description));
                            }
                            echo('</h6>');
                            echo('</div>');
                            echo('<div class="col-md-6 text-right">');
                            echo('<h5>'.Html::encode($v->created_at).'</h5>');
                            echo('</div>');
                        echo('</div>');
                    echo('</div>');
                    echo('<div class="panel-body" style="padding:2%">');
                    echo(Html::encode($v->comment));
                    echo('</div>');
                echo('</div>');
            }
        }
    ?>
    </div>

</div>