backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use common\models\LoginForm;
use yii\filters\VerbFilter;
use yii\helpers\Url;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function actionIndex()
    {
    	foreach (Yii::$app->authManager->getRolesByUser(Yii::$app->user->ID) as $user_role) {
            switch ($user_role->name) {
                case 'administrator': {
                    $this->redirect(Url::home().'administrator');
                }break;
                case 'author': {
                    $this->redirect(Url::home().'author');
                }break;
                case 'editor': {
                    $this->redirect(Url::home().'editor');
                }break;
                /*default: {
                    return $this->goBack();
                }break;*/
            }
        }
        return $this->render('index');
    }

    public function actionLogin()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
        	foreach (Yii::$app->authManager->getRolesByUser(Yii::$app->user->ID) as $user_role) {
                switch ($user_role->name) {
                    case 'administrator': {
                        $this->redirect(Url::home().'administrator');
                    }break;
                    case 'author': {
                        $this->redirect(Url::home().'author');
                    }break;
                    case 'editor': {
                        $this->redirect(Url::home().'editor');
                    }break;
                    default: {
                        return $this->goBack();
                    }break;
                }
            }
            //return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use Yii;

use yii\data\ActiveDataProvider;
use yii\helpers\Html;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\NotFoundHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\helpers\Url;

use common\models\LoginForm;
use common\models\Post;
use common\models\Page;
use common\models\Author;
use common\models\User;
use common\models\ArticleSearch;

use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;
use frontend\models\Contact;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup'],
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'frontend\components\MathCaptchaAction',
                'minLength' => 0,
                'maxLength' => 10,
                //'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        $feedBack = new ContactForm();
        $news = Post::find()
            ->where('status = 1 AND publish_date <= CURDATE()')
            ->limit(3)
            ->orderBy(['publish_date' => SORT_DESC])
            ->all();
        $slideNews = Post::find()
            ->where('is_presentation = 1 AND status = 1 AND publish_date <= CURDATE()')
            ->orderBy(['publish_date' => SORT_DESC])
            ->all();
		return $this->render('index', [
            'news' => $news,
            'slide_news' => $slideNews,
            'feedBack' => $feedBack,
        ]);
    }
	/**
    * Renders single post
    *
    * @return mixed
    */
    public function actionPost($id){   
        $post = Post::findOne($id);

        return $this->render('post', [
            'current' => $post
        ]);
    }
    /**
    * Renders single page
    *
    * @return mixed
    */
    public function actionPage($id) {
        $page = Page::find()
            ->where('id = :id AND status = 1', [':id' => $id])
            ->one();
        if ($page !== null) {
            return $this->render('page', [
                'page' => $page
            ]);
        } else {
            throw new NotFoundHttpException('Страница не найдена.');
        }
    }
    /**
     * Logs in a user.
     *
     * @return mixed
     */
    public function actionLogin()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            //redirect to user module
            foreach (Yii::$app->authManager->getRolesByUser(Yii::$app->user->ID) as $user_role) {
                switch ($user_role->name) {
                    case 'administrator': {
                        $this->redirect(Url::home().'control-panel/administrator');
                    }break;
                    case 'author': {
                        $this->redirect(Url::home().'control-panel/author');
                    }break;
                    case 'editor': {
                        $this->redirect(Url::home().'control-panel/editor');
                    }break;
                    /*default: {
                        return $this->goBack();
                    }break;*/
                }
            }
            //return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logs out the current user.
     *
     * @return mixed
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return mixed
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate() && Yii::$app->request->isPjax) {
            if ($model->sendEmail(Yii::$app->params['adminEmail'])) {
                return $this->renderPartial('message', [
                    'type' => 'success',
                    'message' => 'Спасибо за обращение к нам. Мы ответим как можно быстрее.'
                ]);
            } else {
                return $this->renderPartial('message', [
                    'type' => 'danger',
                    'message' => 'Ошибка при отправке сообщения.'
                ]);
            }
            if (!Yii::$app->request->isPjax) {
                return $this->refresh();
            }
        } else {
            $this->redirect(Url::home());
        }

    }

    /**
     * Displays about page.
     *
     * @return mixed
     */
    public function actionAbout()
    {
        return $this->render('about');
    }

    /**
     * Signs user up.
     *
     * @return mixed
     */
    public function actionSignup()
    {
    	$model = new SignupForm();
    	
        if ($model->load(Yii::$app->request->post())) {
    		if ($user = $model->signup()) {
                if (Yii::$app->getUser()->login($user)) {
                    if(mkdir("./".Yii::$app->params['uploads'].Yii::getAlias('@articlesPath')."/".Yii::$app->user->identity->id."/")){
                        $this->sendEmail($user, $model->password);
                        return $this->redirect(Url::home().'control-panel');
                    }
                }
            }
    	}
    	return $this->render('signup', [
            'model' => $model,
        ]);
    }

    protected function sendEmail($user, $password)
    {
        return \Yii::$app->mailer->compose(['html' => 'afterRegistrationHelloMail-html', 
            'text' => 'afterRegistrationHelloMail-text'], 
            ['user' => $user, 'password' => $password])
            ->setFrom([\Yii::$app->params['adminEmail'] => 'IT&Transport'])
            ->setTo($user->email)
            ->setSubject(Html::encode('Регистрация на IT&Транспорт'))
            ->send();
    }

    /**
     * Requests password reset.
     *
     * @return mixed
     */
    public function actionRequestPasswordReset()
    {
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Check your email for further instructions.');

                return $this->goHome();
            } else {
                Yii::$app->session->setFlash('error', 'Sorry, we are unable to reset password for email provided.');
            }
        }

        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    /**
     * Resets password.
     *
     * @param string $token
     * @return mixed
     * @throws BadRequestHttpException
     */
    public function actionResetPassword($token)
    {
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->session->setFlash('success', 'New password was saved.');

            return $this->goHome();
        }

        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }

    public function actionSearch()
    {
        $this->layout = 'search';
        
        $searchModel = new ArticleSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('article', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }	
}

frontend/views/site/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\ArticleSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="article-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'title') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <?php // echo $form->field($model, 'status') ?>

    <?php // echo $form->field($model, 'payment_status') ?>

    <?php echo $form->field($model, 'tags') ?>

    <?php // echo $form->field($model, 'digest_id') ?>

    <?php // echo $form->field($model, 'rus_annotation') ?>

    <?php // echo $form->field($model, 'eng_annotation') ?>

    <?php echo $form->field($model, 'coauthor') ?>

    <?php // echo $form->field($model, 'science_id') ?>

    <?php echo $form->field($model, 'organization') ?>

    <?php // echo $form->field($model, 'grnti') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>This is the About page. You may modify the following file to customize its content:</p>

    <code><?= __FILE__ ?></code>
</div>

frontend/views/site/article.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel common\models\ArticleSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Articles';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="article-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Create Article', ['create'], ['class' => 'btn btn-success']) ?>
    </p>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            'title',
            'author_id',
            //'udk_index',
            //'pages',
            // 'created_at',
            // 'updated_at',
            'status',
            // 'payment_status',
            // 'tags',
            // 'digest_id',
            // 'rus_annotation:ntext',
            // 'eng_annotation:ntext',
            'coauthor',
            'science_id',
            'organization',
            // 'grnti',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
</div>

frontend/views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Контакты';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="container">
    <div class="site-contact form-padding">
        <div class="panel panel-default">
            <div class="panel-heading text-center">
                <h1><?= Html::encode($this->title) ?></h1>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-12">
                        <p>Если у Вас есть вопрос или предложение, свяжитесь с нами заполнив форму:</p>
                        <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>
                            
                            <?= $form->field($model, 'name') ?>

                            <?= $form->field($model, 'email') ?>

                            <?= $form->field($model, 'subject') ?>

                            <?= $form->field($model, 'body')->textArea(['rows' => 6]) ?>

                            <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                                'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                            ]) ?>

                            <div class="form-group">
                                <?= Html::submitButton('Отправить', ['class' => 'btn btn-default', 'name' => 'contact-button']) ?>
                            </div>

                        <?php ActiveForm::end(); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>	
</div>

frontend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>

<div class="container">
    <div class="site-error site-page">

        <h1><?= Html::encode($this->title) ?></h1>

        <div class="alert alert-danger">
            <?= nl2br(Html::encode($message)) ?>
        </div>

        <p>
            The above error occurred while the Web server was processing your request.
        </p>
        <p>
            Please contact us if you think this is a server error. Thank you.
        </p>

    </div>
</div>

frontend/views/site/index.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;
use yii\widgets\Pjax;

$this->title = \Yii::$app->params['siteTtitle'];
?>

<section class="top-section">
    <div class="container"> 
        <div class="row">
             <div class="col-md-3">
                    <div class="col-md-12">
            <a class="btn btn-social-icon btn-vk">
             <span class="fa fa-vk"></span>
            </a>
            <a class="btn btn-social-icon btn-facebook">
             <span class="fa fa-facebook"></span>
            </a>
            <a class="btn btn-social-icon btn-twitter">
             <span class="fa fa-twitter"></span>
            </a>
            <a class="btn btn-social-icon btn-google">
             <span class="fa fa-google"></span>
            </a>
            
            </div>
            </div>
             <div class="col-md-6">
                    <div class="logo text-center">
                    <img src="/mediafiles/files/its.png" />
                 </div>
            </div>
            <div class="col-md-3">
                <div class="pull-right apply-block">

                    <?= Html::beginTag('a', ['href' => Url::to(['control-panel/author'], true)]) ?>

                        <button class="btn btn-default btn-lg apply-button well btn-block" type="button"  aria-expanded="false">Опубликовать статью в сборнике «IT&nbsp;&&nbsp;Транспорт»</button>

                    <?= Html::endTag('a') ?>

                    <?= Html::beginTag('a', ['href' => Url::to(['control-panel/author'], true)]) ?>

                        <button class="btn btn-default btn-lg apply-button well btn-block" type="button"  aria-expanded="false">Принять участие в конкурсе «IT&nbsp;&&nbsp;Транспорт»</button>

                    <?= Html::endTag('a') ?>

                </div>
            </div>

        </div>
        <div class="row">
            <div class="col-md-12">

                <?php if (isset($slide_news) && count($slide_news) !== 0) { ?>

                            <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                                <!-- Indicators -->
                                <ol class="carousel-indicators">

                                    <?php foreach ($slide_news as $key=>$slide) { ?>

                                            <li data-target="#carousel-example-generic" data-slide-to="<?php echo $key; ?>" class="<?php if ($key == 0) echo 'active'; ?>"></li>

                                    <?php } ?>

                                </ol>
                                <!-- Wrapper for slides -->
                                <div class="carousel-inner" role="listbox">

                                    <?php foreach ($slide_news as $key => $slide) { ?>

                                        <div class="item  <?php if ($key == 0) echo 'active';  ?> ">
                                            <div class="main-article">
                                                <div class="article-header text-center">

                                                    <?= Html::a('<h1>'.Html::decode($slide->title).'</h1>', ['site/post', 'id' => $slide->id]) ?>

                                                </div>
                                            </div>
                                        </div>

                                    <?php } ?>

                                </div>
                                <!-- Controls -->
                                <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
                                    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                                    <span class="sr-only"><<</span>
                                </a>
                                <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
                                    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                                    <span class="sr-only">>></span>
                                </a>
                            </div>

                <?php } ?>        
                            
            </div>
        </div>
    </div>
</section>
<section class="middle-section">
        <div class="container"> 
            <div class="row row-eq-height">
                <?php
                    if (isset($news)) {
                        foreach ($news as $post) { ?>

                            <div class="col-xs-6 col-md-4 thumbnail">

                                <?= Html::beginTag('a', ['href' => Url::to(['site/post', 'id' => $post->id], true)]) ?>

                                    <?= Html::img(Html::encode($post->thumbnail), ['alt' => 'Preview']) ?>

                                <?= Html::endTag('a') ?>

                              <div class="caption">

                                <?= Html::tag('time', Html::encode($post->publish_date)) ?>

                                <?= Html::tag('h3', Html::encode(strip_tags($post->title))) ?>

                                <?= Html::beginTag('article', ['class' => 'post-preview']) ?>

                                    <?= Html::tag('p', Html::decode($post->preview)) ?>

                                <?= Html::endTag('article') ?>

                                <?= Html::beginTag('p') ?>
                                    
                                    <?= Html::a('Подробнее...', ['site/post', 'id' => $post->id], ['class' => 'btn btn-default thumb-bottom-button', 'role' => 'button']) ?>

                                <?= Html::endTag('p') ?>

                              </div>
                    
                            </div>

                    <?php }
                    }
                ?>
            </div>
        </div>
</section>
<section class="contact-section" id="contacts">
    <?php
        $this->registerJs(
            '$("document").ready(function(){
                $("#contact-form").on("pjax:end", function() {
                    $.pjax.reload({container:"#feedback-result"});
                });
            $(".contact-toggle").click(function(){
                    $(".contact-toggled").slideToggle("linear");
                });
            });'
        );
    ?>

    <div class="container text-center"> 
        <div class="section-header contact-toggle">
            <span class="white-text">Связаться с нами</span>
        </div>
        <div class="contact-toggled">
        <div class="row">
            <div id="feedback-result" class="col-md-12">
            </div>
        </div>
        <div class="row">

            <?php Pjax::begin(['id' => 'feedBack']) ?>

                <?php $form = ActiveForm::begin(['action' => ['site/contact'], 'id' => 'contact-form', 'options' => ['data-pjax' => true]]); ?>

                        <div class="col-lg-4 col-sm-4" >

                            <?= $form->field($feedBack, 'name') ?>

                        </div>
                        <div class="col-lg-4 col-sm-4 " >

                            <?= $form->field($feedBack, 'email') ?>

                        </div>
                        <div class="col-lg-4 col-sm-4">

                            <?= $form->field($feedBack, 'subject') ?>

                        </div>
                        <div class="col-lg-12 col-sm-12" >
                        
                            <?= $form->field($feedBack, 'body')->textArea(['rows' => 6]) ?>

                        </div>
                        <div class="col-lg-12 col-sm-12" >
                        
                            <?= $form->field($feedBack, 'verifyCode')->widget(Captcha::className(), [
                                    'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                            ]) ?>

                        </div>
                        <div class="col-lg-12 col-sm-12">
                            
                            <?= Html::submitButton('ОТПРАВИТЬ', ['class' => 'btn btn-primary custom-button', 'name' => 'contact-button']) ?>

                        </div>


                <?php ActiveForm::end(); ?>

            <?php Pjax::end(); ?>

        </div>
    </div> </div>
</section>
<!-- <section class="info-section">
    <div class="container text-center"> 
        <div class="section-header">
            <h2 class="black-text">Контактная информация</h2></div>
      
        <div class="contacts-info-table text-left">
            <ul class="list-group">
              <li class="list-group-item"><span class="glyphicon glyphicon-user" aria-hidden="true"></span> ИнтелТранс</li>
              <li class="list-group-item"><span class="glyphicon glyphicon-map-marker" aria-hidden="true"></span> Россия, г.Самара, ул. Мичурина, 126</li>
              <li class="list-group-item"><span class="glyphicon glyphicon-phone-alt" aria-hidden="true"></span> (846) 922-79-78</li>
              <li class="list-group-item"><span class="glyphicon glyphicon-send" aria-hidden="true"></span> info@its-spc.ru</li>   
            </ul>  
        </div>
        <div class="row">
            <div class="col-md-12">
            <a class="btn btn-social-icon btn-vk">
             <span class="fa fa-vk"></span>
            </a>
            <a class="btn btn-social-icon btn-facebook">
             <span class="fa fa-facebook"></span>
            </a>
            <a class="btn btn-social-icon btn-twitter">
             <span class="fa fa-twitter"></span>
            </a>
            <a class="btn btn-social-icon btn-google">
             <span class="fa fa-google"></span>
            </a>
            <a class="btn btn-social-icon btn-bitbucket">
             <span class="fa fa-bitbucket"></span>
            </a>
            </div>
        </div>
    </div>
</section> -->

frontend/views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Вход';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="container">
    <div class="site-login form-padding">
        <div class="panel panel-default">
            <div class="panel-heading text-center">
                <h1 style="padding:0"><?= Html::encode($this->title) ?></h1>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-lg-12">
                        <?php $form = ActiveForm::begin(['id' => 'login-form']); ?>

                            <?= $form->field($model, 'username') ?>

                            <?= $form->field($model, 'password')->passwordInput() ?>
                            <div class="row text-right">
                                <div class="col-md-12">
                                    <?= $form->field($model, 'rememberMe')->checkbox() ?>
                                </div>
                            </div>
                            <div style="color:#999;margin:1em 0" class="text-right">
                                Если Вы забыли пароль, Вы можете <?= Html::a('сбросить его', ['site/request-password-reset']) ?>.
                            </div>

                            <div class="form-group text-right">
                                <?= Html::submitButton('Войти', ['class' => 'btn btn-default', 'name' => 'login-button']) ?>
                            </div>

                        <?php ActiveForm::end(); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

frontend/views/site/message.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

?>

<div class="container">

        <div class="alert alert-<?= ($type) ? ($type) : ('undefined') ?>">
            <?= nl2br(Html::encode($message)) ?>
        </div>

</div>

frontend/views/site/page.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ContactForm */

use yii\helpers\Html;
use yii\widgets\Breadcrumbs;
?>

<div class="container">
    <div class="site-page form-padding">
        <?php if (isset($page)) { ?>

                    <?php 

                        $this->title = $page->title;
                        $this->params['breadcrumbs'][] = $this->title;

                    ?>

                    <?= 

                        Breadcrumbs::widget([
                            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
                        ]) 
                        
                    ?>

                <!--renderView-->
                <?php
                    if ($page->layout && file_exists($page->layout)) { ?>

                        <?= 
                            $this->renderFile($page->layout, [
                                'page' => $page
                            ]) 
                        ?>

                <?php } else { ?>

                        <?= Html::decode($page->page_body) ?>

                <?php } ?>

        <?php } ?>
    </div>	
</div>

frontend/views/site/post.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ContactForm */

use yii\helpers\Html;



//$this->title = 'Контакты';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="container">
    <div class="site-contact form-padding">
        <div class="panel panel-default">
            <?php if (isset($current)) {  ?>
                <div class="panel-heading text-center">

                    <?= Html::tag('h3', Html::encode($current->title)) ?>

                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-12">

                            <?= Html::tag('article', Html::decode($current->content), ['class' => 'post-preview']) ?>

                        </div>
                    </div>
                </div>
            <?php } ?>   
        </div>
    </div>	
</div>